package com.elsealabs.xshot.annotation;

import java.util.ArrayList;
import java.util.List;

/**
 * AnnotationEngine.java
 * 
 * Keeps track of annotations generated by mouse clicks, mouse drags, and
 * key events that change that engine's state.
 * 
 * @author Connor Elsea (@Connorelsea)
 */
public class AnnotationEngine
{
	private List<Annotation> annotations;
	
	public static enum STATE
	{
		NONE, LINE, ARROW
	}
	private STATE state;
	
	public AnnotationEngine()
	{
		annotations = new ArrayList<Annotation>();
	}
	
	public STATE getState()
	{
		return state;
	}
	
	public void setState(STATE state)
	{
		this.state = state;
	}
}