package com.elsealabs.xshot.annotation;

import java.util.ArrayList;
import java.util.List;

import javax.swing.JComponent;

/**
 * AnnotationEngine.java
 * 
 * Keeps track of annotations generated by mouse clicks, mouse drags, and
 * key events that change that engine's state.
 * 
 * @author Connor Elsea (@Connorelsea)
 */
public class AnnotationEngine
{
	private List<Annotation> annotations;
	
	private AnnotationMouseListener       mouseListener;
	private AnnotationMouseMotionListener mouseMotionListener;
	
	public static enum STATE
	{
		NONE, LINE, ARROW
	}
	private STATE state;
	
	public AnnotationEngine()
	{
		annotations = new ArrayList<Annotation>();
	}
	
	/**
	 * Sets up the specified component to work as input for the Annotation Engine.
	 * 
	 * @param component The specified component to set up.
	 */
	public void addTo(JComponent component)
	{
		addListenersTo(component);
	}
	
	/**
	 * Adds the required key listeners to the specified component.
	 * 
	 * @param component The component to add the listeners to.
	 */
	public void addListenersTo(JComponent component)
	{
		mouseListener 		= new AnnotationMouseListener();
		mouseMotionListener = new AnnotationMouseMotionListener();
		
		component.addMouseListener(mouseListener);
		component.addMouseMotionListener(mouseMotionListener);
	}
	
	public STATE getState()
	{
		return state;
	}
	
	public void setState(STATE state)
	{
		this.state = state;
	}
}